fix: wrong entry point in package.json
It was impossible to require the module as a npm package. For example:
```
var pbjs = require('prebid.js');
```
caused the error: Cannot find module 'prebid.js'
So it was impossible to use with Browserify/Webpack.